// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoListApp.Data;

#nullable disable

namespace ToDoListApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240711193626_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDoListApp.Models.Priority", b =>
                {
                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Level"));

                    b.HasKey("Level");

                    b.ToTable("Priorities");

                    b.HasData(
                        new
                        {
                            Level = 1
                        },
                        new
                        {
                            Level = 2
                        },
                        new
                        {
                            Level = 3
                        },
                        new
                        {
                            Level = 4
                        },
                        new
                        {
                            Level = 5
                        });
                });

            modelBuilder.Entity("ToDoListApp.Models.ToDoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PriorityId");

                    b.HasIndex("UserId");

                    b.ToTable("ToDoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description for Task 1",
                            DueDate = new DateTime(2024, 7, 12, 22, 36, 25, 76, DateTimeKind.Local).AddTicks(8922),
                            IsCompleted = false,
                            PriorityId = 1,
                            Title = "Task 1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description for Task 2",
                            DueDate = new DateTime(2024, 7, 13, 22, 36, 25, 76, DateTimeKind.Local).AddTicks(8940),
                            IsCompleted = true,
                            PriorityId = 2,
                            Title = "Task 2",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description for Task 3",
                            DueDate = new DateTime(2024, 7, 14, 22, 36, 25, 76, DateTimeKind.Local).AddTicks(8943),
                            IsCompleted = false,
                            PriorityId = 3,
                            Title = "Task 3",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description for Task 4",
                            DueDate = new DateTime(2024, 7, 15, 22, 36, 25, 76, DateTimeKind.Local).AddTicks(8944),
                            IsCompleted = true,
                            PriorityId = 4,
                            Title = "Task 4",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description for Task 5",
                            DueDate = new DateTime(2024, 7, 16, 22, 36, 25, 76, DateTimeKind.Local).AddTicks(8946),
                            IsCompleted = false,
                            PriorityId = 5,
                            Title = "Task 5",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("ToDoListApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Charlie"
                        },
                        new
                        {
                            Id = 4,
                            Name = "David"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Eve"
                        });
                });

            modelBuilder.Entity("ToDoListApp.Models.ToDoItem", b =>
                {
                    b.HasOne("ToDoListApp.Models.Priority", "Priority")
                        .WithMany("ToDoItems")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToDoListApp.Models.User", "User")
                        .WithMany("ToDoItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Priority");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToDoListApp.Models.Priority", b =>
                {
                    b.Navigation("ToDoItems");
                });

            modelBuilder.Entity("ToDoListApp.Models.User", b =>
                {
                    b.Navigation("ToDoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
